[package]
name = "prox_parser"
version = "0.0.0"
edition = "2024"

[dependencies]
tracing = { workspace = true }

prox_interner = { workspace = true }
prox_lexer = { workspace = true }

[lints]
workspace = true
