[package]
name = "prox_walker"
version = "0.0.0"
edition = "2024"

[dependencies]
tracing = { workspace = true }
# Delete this after done testing
tracing-subscriber = { workspace = true }

prox_interner = { workspace = true }
prox_parser = { workspace = true }

[lints]
workspace = true
